### ISSUE TITLE
Says server is already closed when it is running

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode-liveserver#35]
1. Open a preview
2. The servers starts
3. Go to the command palette and close the development server
4. 🐛 It says server is already closed
(note it also says Liveserver v2 instead of live preview)

**Comment by andreamah** [comment]
What version of the extension are you using? I removed `Liveserver v2` mentions quite a while ago.

**Comment by lramos15** [comment]
Awkward. I had both the marketplace and the old one installed.

**Comment by andreamah** [comment]
Haha, that's ok! Does #34 still happen when you have the latest version? There may be some port bugs, but the one you pointed out was not one I could replicate.
